name: SonarQube Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' # Replace with your .NET version

    - name: Build the project
      run: |
        dotnet restore MyDotnetApp/MyDotnetApp.csproj
        dotnet build MyDotnetApp/MyDotnetApp.csproj --no-restore

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Add SONAR_TOKEN in GitHub Secrets
      with:
        projectBaseDir: MyDotnetApp # Path to the project directory
        args: |
          -Dsonar.projectKey=<project-key> \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
