name: .NET Build and SonarQube Analysis

on:
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      # Step 3: Install SonarScanner for .NET
      - name: Install SonarScanner for .NET
        run: |
          dotnet tool install --global dotnet-sonarscanner

      # Step 4: Start SonarQube Analysis (Begin Step)
      - name: Begin SonarQube Analysis
        run: |
          dotnet sonarscanner begin `
            /k:"sonar-dotnet-scan" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="${{ secrets.SONAR_URL }}" `
            /o:"sonar-ad111"

      # Step 5: Build the Project
      - name: Build the Project
        run: |
          dotnet build

      # Step 6: End SonarQube Analysis
      - name: End SonarQube Analysis
        run: |
          dotnet sonarscanner end `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
